spring:
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
    username: postgres.svxdmuthiycwgqgxpwyn
    password: ${SUPABASE_DB_PASSWORD}

app:
  demo-mode: true